# Site settings
title: DJ Greenfield's Blog
email: Mr.Kaitryn.Dale@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. I'm a recent Turing graduate who enjoys playing video games,
  opposing gators, living in Colorado, and obsessively coding. Most of my posts
  revolve around coding or gaming with a few miscellaneous bits tossed about.
  Feel free to hit me up via email anytime!
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: AllPurposeDJ
github_username:  AllPurposeName
linked_in:  AllPurposeName
  # Build settings
markdown: kramdown
